name: Deploy App
on: 
  push:
    branches:
    - main
    
jobs:  
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets presence
        run: |
          echo "Client: ${TAILSCALE_AUTH_CLIENT:+[set]}"
          echo "Secret: ${TAILSCALE_AUTH_SECRET:+[set]}"
        env:
          TAILSCALE_AUTH_CLIENT: ${{ secrets.TAILSCALE_AUTH_CLIENT }}
          TAILSCALE_AUTH_SECRET: ${{ secrets.TAILSCALE_AUTH_SECRET }}
    
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_AUTH_CLIENT }}
          oauth-secret: ${{ secrets.TAILSCALE_AUTH_SECRET }}
          version: 1.66.4
  
      - name: Add SSH Key
        id: ssh
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
  
      - name: Add Server to known hosts
        run: |
          ssh -o StrictHostKeyChecking=no latte@uon-marketplace.taild171a.ts.net 'bash -s' < ./scripts/deploy.sh
