name: Deploy App
on: 
  push:
    branches:
    - main
    
jobs:  
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
  
      - name: Add SSH Key
        id: ssh
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
  
      - name: Add Server to known hosts
        run: |
          ssh -o StrictHostKeyChecking=no latte@uon-marketplace.taild171a.ts.net 'bash -s' < ./scripts/deploy.sh
